#!/bin/bash

# Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
BLUE='\033[0;34m'
NC='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'

echo ""
echo -e "${MAGENTA}╔═══════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${MAGENTA}║${NC}                                                                       ${MAGENTA}║${NC}"
echo -e "${MAGENTA}║${NC}   ${BOLD}🚀 CURSOR COMMAND CENTER${NC}                                           ${MAGENTA}║${NC}"
echo -e "${MAGENTA}║${NC}   ${DIM}Your AI-Powered Multi-Repo Development Hub${NC}                         ${MAGENTA}║${NC}"
echo -e "${MAGENTA}║${NC}                                                                       ${MAGENTA}║${NC}"
echo -e "${MAGENTA}╚═══════════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${DIM}Usage:${NC} ${BOLD}./cc${NC} ${GREEN}<command>${NC} ${DIM}[options]${NC}"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  COMMANDS${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "setup" "Run the first-time setup wizard"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "open" "Open a workspace in Cursor"
printf "  ${DIM}%-12s${NC} %s\n" "  --last, -l" "Re-open your last workspace"
printf "  ${DIM}%-12s${NC} %s\n" "  [name]" "Open specific workspace directly"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "graph" "Generate service dependency graph"
printf "  ${DIM}%-12s${NC} %s\n" "  --open, -o" "Generate and open in browser"
printf "  ${DIM}%-12s${NC} %s\n" "  --view, -v" "View existing graph (skip generate)"
printf "  ${DIM}%-12s${NC} %s\n" "  [workspace]" "Specific workspace"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "status" "Check git status across all repos"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "add" "Add repos to an existing project"
printf "  ${GREEN}%-12s${NC} %s\n" "remove" "Remove repos from a project"
printf "  ${GREEN}%-12s${NC} %s\n" "rename" "Rename a workspace (old → new)"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "export" "Export config for backup/sharing"
printf "  ${GREEN}%-12s${NC} %s\n" "import" "Import config from exported file"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "manage" "Rescan repos, regenerate workspaces"
printf "  ${GREEN}%-12s${NC} %s\n" "start" "Quick start (defaults to 'all')"
printf "  ${GREEN}%-12s${NC} %s\n" "help" "Show this help message"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  EXAMPLES${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${DIM}\$${NC} ./cc setup              ${DIM}# First-time setup wizard${NC}"
echo -e "  ${DIM}\$${NC} ./cc open               ${DIM}# Show workspace menu${NC}"
echo -e "  ${DIM}\$${NC} ./cc open --last        ${DIM}# Re-open last workspace${NC}"
echo -e "  ${DIM}\$${NC} ./cc open backend       ${DIM}# Open 'backend' directly${NC}"
echo -e "  ${DIM}\$${NC} ./cc graph --view       ${DIM}# View existing graph${NC}"
echo -e "  ${DIM}\$${NC} ./cc graph cspm --open  ${DIM}# Generate & open in browser${NC}"
echo -e "  ${DIM}\$${NC} ./cc status             ${DIM}# Git status for all repos${NC}"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  TIPS${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${CYAN}•${NC} Use ${BOLD}@Codebase${NC} in Cursor to search all repos at once"
echo -e "  ${CYAN}•${NC} Task history is auto-saved in ${DIM}task-history/[workspace]/${NC}"
echo -e "  ${CYAN}•${NC} Graphs are auto-generated when creating workspaces"
echo -e "  ${CYAN}•${NC} Short aliases: ${GREEN}o${NC}pen, ${GREEN}s${NC}tatus, ${GREEN}m${NC}anage, ${GREEN}g${NC}raph"
echo ""
echo -e "${DIM}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${DIM}  github.com/lionelresnik/cursor-command-center${NC}"
echo ""
