#!/bin/bash

# Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
BLUE='\033[0;34m'
NC='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'

echo ""
echo -e "${MAGENTA}╔═══════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${MAGENTA}║${NC}                                                                       ${MAGENTA}║${NC}"
echo -e "${MAGENTA}║${NC}   ${BOLD}🚀 CURSOR COMMAND CENTER${NC}                                           ${MAGENTA}║${NC}"
echo -e "${MAGENTA}║${NC}   ${DIM}Your AI-Powered Multi-Repo Development Hub${NC}                         ${MAGENTA}║${NC}"
echo -e "${MAGENTA}║${NC}                                                                       ${MAGENTA}║${NC}"
echo -e "${MAGENTA}╚═══════════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${DIM}Usage:${NC} ${BOLD}./cc${NC} ${GREEN}<command>${NC} ${DIM}[options]${NC}"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  COMMANDS${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "setup" "Run the first-time setup wizard"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "open" "Open a workspace in Cursor"
printf "  ${DIM}%-12s${NC} %s\n" "  --last, -l" "Re-open your last workspace"
printf "  ${DIM}%-12s${NC} %s\n" "  [name]" "Open specific workspace directly"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "graph" "Generate service dependency graph"
printf "  ${DIM}%-12s${NC} %s\n" "  --open, -o" "Generate and open in browser"
printf "  ${DIM}%-12s${NC} %s\n" "  --view, -v" "View existing graph (skip generate)"
printf "  ${DIM}%-12s${NC} %s\n" "  [workspace]" "Specific workspace"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "status" "Check git status across all repos"
printf "  ${DIM}%-12s${NC} %s\n" "  --pull, -p" "Auto-pull repos that are behind (if clean)"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "new" "Create a new workspace (guided setup)"
printf "  ${GREEN}%-12s${NC} %s\n" "add" "Add repos to an existing project"
printf "  ${GREEN}%-12s${NC} %s\n" "remove" "Remove repos from a project"
printf "  ${GREEN}%-12s${NC} %s\n" "rename" "Rename a workspace (old → new)"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "todo" "Manage your persistent todo list"
printf "  ${DIM}%-12s${NC} %s\n" "  add <desc>" "Add a todo (-w workspace, -p priority)"
printf "  ${DIM}%-12s${NC} %s\n" "  start [n]" "Move item to In Progress"
printf "  ${DIM}%-12s${NC} %s\n" "  done [n]" "Mark item as done"
printf "  ${DIM}%-12s${NC} %s\n" "  next" "Show what's next"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "standup" "Generate standup summary"
printf "  ${DIM}%-12s${NC} %s\n" "  daily" "Today's standup (default)"
printf "  ${DIM}%-12s${NC} %s\n" "  weekly" "Weekly recap"
printf "  ${DIM}%-12s${NC} %s\n" "  view" "View most recent standup"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "sync" "Sync plugin components & update features"
printf "  ${DIM}%-12s${NC} %s\n" "  --plugin" "Only sync plugin components"
printf "  ${DIM}%-12s${NC} %s\n" "  --data" "Only initialize data files"
printf "  ${DIM}%-12s${NC} %s\n" "  --workspaces" "Only fix workspace files"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "export" "Export config for backup/sharing"
printf "  ${GREEN}%-12s${NC} %s\n" "import" "Import config from exported file"
echo ""
printf "  ${GREEN}%-12s${NC} %s\n" "manage" "Rescan repos, regenerate workspaces"
printf "  ${GREEN}%-12s${NC} %s\n" "start" "Quick start (defaults to 'all')"
printf "  ${GREEN}%-12s${NC} %s\n" "help" "Show this help message"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  EXAMPLES${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${DIM}\$${NC} ./cc setup              ${DIM}# First-time setup wizard${NC}"
echo -e "  ${DIM}\$${NC} ./cc sync               ${DIM}# Update to latest features${NC}"
echo -e "  ${DIM}\$${NC} ./cc open               ${DIM}# Show workspace menu${NC}"
echo -e "  ${DIM}\$${NC} ./cc open --last        ${DIM}# Re-open last workspace${NC}"
echo -e "  ${DIM}\$${NC} ./cc new                ${DIM}# Create new workspace${NC}"
echo -e "  ${DIM}\$${NC} ./cc graph --view       ${DIM}# View existing graph${NC}"
echo -e "  ${DIM}\$${NC} ./cc status             ${DIM}# Git status for all repos${NC}"
echo -e "  ${DIM}\$${NC} ./cc todo add fix auth  ${DIM}# Add a todo${NC}"
echo -e "  ${DIM}\$${NC} ./cc standup            ${DIM}# Generate daily standup${NC}"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  TIPS${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${CYAN}•${NC} Use ${BOLD}@Codebase${NC} in Cursor to search all repos at once"
echo -e "  ${CYAN}•${NC} Task history is auto-saved in ${DIM}task-history/[workspace]/${NC}"
echo -e "  ${CYAN}•${NC} Graphs are auto-generated when creating workspaces"
echo -e "  ${CYAN}•${NC} Short aliases: ${GREEN}o${NC}pen, ${GREEN}s${NC}tatus, ${GREEN}m${NC}anage, ${GREEN}g${NC}raph, ${GREEN}t${NC}odo"
echo ""
echo -e "${DIM}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${DIM}  github.com/lionelresnik/cursor-command-center${NC}"
echo ""
